<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="jdt" nsURI="http://www.eclipse.org/oomph/setup/jdt/1.0" nsPrefix="jdt">
  <eAnnotations source="http://www.eclipse.org/emf/2002/Ecore">
    <details key="schemaLocation" value="http://git.eclipse.org/c/oomph/org.eclipse.oomph.git/plain/setups/models/JDT.ecore"/>
  </eAnnotations>
  <eAnnotations source="http://www.eclipse.org/oomph/setup/Enablement">
    <details key="variableName" value="setup.jdt.p2"/>
    <details key="repository" value="${oomph.update.url}"/>
    <details key="installableUnits" value="org.eclipse.oomph.setup.jdt.feature.group"/>
  </eAnnotations>
  <eAnnotations source="http://www.eclipse.org/oomph/base/LabelProvider">
    <details key="imageBaseURI" value="http://git.eclipse.org/c/oomph/org.eclipse.oomph.git/plain/plugins/org.eclipse.oomph.setup.jdt.edit/icons/full/obj16"/>
  </eAnnotations>
  <eClassifiers xsi:type="ecore:EClass" name="JRETask" eSuperTypes="http://www.eclipse.org/oomph/setup/1.0#//SetupTask">
    <eAnnotations source="http://www.eclipse.org/oomph/setup/ValidTriggers">
      <details key="triggers" value="STARTUP MANUAL"/>
    </eAnnotations>
    <eAnnotations source="http://www.eclipse.org/oomph/setup/Variable">
      <eAnnotations source="Choice">
        <details key="value" value="${jre.location-1.2}"/>
        <details key="label" value="JRE 1.2 Location"/>
      </eAnnotations>
      <eAnnotations source="Choice">
        <details key="value" value="${jre.location-1.3}"/>
        <details key="label" value="JRE 1.3 Location"/>
      </eAnnotations>
      <eAnnotations source="Choice">
        <details key="value" value="${jre.location-1.4}"/>
        <details key="label" value="JRE 1.4 Location"/>
      </eAnnotations>
      <eAnnotations source="Choice">
        <details key="value" value="${jre.location-1.5}"/>
        <details key="label" value="JRE 1.5 Location"/>
      </eAnnotations>
      <eAnnotations source="Choice">
        <details key="value" value="${jre.location-1.6}"/>
        <details key="label" value="JRE 1.6 Location"/>
      </eAnnotations>
      <eAnnotations source="Choice">
        <details key="value" value="${jre.location-1.7}"/>
        <details key="label" value="JRE 1.7 Location"/>
      </eAnnotations>
      <eAnnotations source="Choice">
        <details key="value" value="${jre.location-1.8}"/>
        <details key="label" value="JRE 1.8 Location"/>
      </eAnnotations>
      <details key="name" value="jre.location-1.1"/>
      <details key="type" value="FOLDER"/>
      <details key="label" value="JRE 1.1 Location"/>
      <details key="description" value="The location of a JDK or JRE compatible with Java 1.1."/>
    </eAnnotations>
    <eAnnotations source="http://www.eclipse.org/oomph/setup/Variable">
      <eAnnotations source="Choice">
        <details key="value" value="${jre.location-1.3}"/>
        <details key="label" value="JRE 1.3 Location"/>
      </eAnnotations>
      <eAnnotations source="Choice">
        <details key="value" value="${jre.location-1.4}"/>
        <details key="label" value="JRE 1.4 Location"/>
      </eAnnotations>
      <eAnnotations source="Choice">
        <details key="value" value="${jre.location-1.5}"/>
        <details key="label" value="JRE 1.5 Location"/>
      </eAnnotations>
      <eAnnotations source="Choice">
        <details key="value" value="${jre.location-1.6}"/>
        <details key="label" value="JRE 1.6 Location"/>
      </eAnnotations>
      <eAnnotations source="Choice">
        <details key="value" value="${jre.location-1.7}"/>
        <details key="label" value="JRE 1.7 Location"/>
      </eAnnotations>
      <eAnnotations source="Choice">
        <details key="value" value="${jre.location-1.8}"/>
        <details key="label" value="JRE 1.8 Location"/>
      </eAnnotations>
      <details key="name" value="jre.location-1.2"/>
      <details key="type" value="FOLDER"/>
      <details key="label" value="JRE 1.2 Location"/>
      <details key="description" value="The location of a JDK or JRE compatible with Java 1.2."/>
    </eAnnotations>
    <eAnnotations source="http://www.eclipse.org/oomph/setup/Variable">
      <eAnnotations source="Choice">
        <details key="value" value="${jre.location-1.4}"/>
        <details key="label" value="JRE 1.4 Location"/>
      </eAnnotations>
      <eAnnotations source="Choice">
        <details key="value" value="${jre.location-1.5}"/>
        <details key="label" value="JRE 1.5 Location"/>
      </eAnnotations>
      <eAnnotations source="Choice">
        <details key="value" value="${jre.location-1.6}"/>
        <details key="label" value="JRE 1.6 Location"/>
      </eAnnotations>
      <eAnnotations source="Choice">
        <details key="value" value="${jre.location-1.7}"/>
        <details key="label" value="JRE 1.7 Location"/>
      </eAnnotations>
      <eAnnotations source="Choice">
        <details key="value" value="${jre.location-1.8}"/>
        <details key="label" value="JRE 1.8 Location"/>
      </eAnnotations>
      <details key="name" value="jre.location-1.3"/>
      <details key="type" value="FOLDER"/>
      <details key="label" value="JRE 1.3 Location"/>
      <details key="description" value="The location of a JDK or JRE compatible with Java 1.3."/>
    </eAnnotations>
    <eAnnotations source="http://www.eclipse.org/oomph/setup/Variable">
      <eAnnotations source="Choice">
        <details key="value" value="${jre.location-1.5}"/>
        <details key="label" value="JRE 1.5 Location"/>
      </eAnnotations>
      <eAnnotations source="Choice">
        <details key="value" value="${jre.location-1.6}"/>
        <details key="label" value="JRE 1.6 Location"/>
      </eAnnotations>
      <eAnnotations source="Choice">
        <details key="value" value="${jre.location-1.7}"/>
        <details key="label" value="JRE 1.7 Location"/>
      </eAnnotations>
      <eAnnotations source="Choice">
        <details key="value" value="${jre.location-1.8}"/>
        <details key="label" value="JRE 1.8 Location"/>
      </eAnnotations>
      <details key="name" value="jre.location-1.4"/>
      <details key="type" value="FOLDER"/>
      <details key="label" value="JRE 1.4 Location"/>
      <details key="description" value="The location of a JDK or JRE compatible with Java 1.4."/>
    </eAnnotations>
    <eAnnotations source="http://www.eclipse.org/oomph/setup/Variable">
      <eAnnotations source="Choice">
        <details key="value" value="${jre.location-1.6}"/>
        <details key="label" value="JRE 1.6 Location"/>
      </eAnnotations>
      <eAnnotations source="Choice">
        <details key="value" value="${jre.location-1.7}"/>
        <details key="label" value="JRE 1.7 Location"/>
      </eAnnotations>
      <eAnnotations source="Choice">
        <details key="value" value="${jre.location-1.8}"/>
        <details key="label" value="JRE 1.8 Location"/>
      </eAnnotations>
      <details key="name" value="jre.location-1.5"/>
      <details key="type" value="FOLDER"/>
      <details key="label" value="JRE 1.5 Location"/>
      <details key="description" value="The location of a JDK or JRE compatible with Java 1.5."/>
    </eAnnotations>
    <eAnnotations source="http://www.eclipse.org/oomph/setup/Variable">
      <eAnnotations source="Choice">
        <details key="value" value="${jre.location-1.7}"/>
        <details key="label" value="JRE 1.7 Location"/>
      </eAnnotations>
      <eAnnotations source="Choice">
        <details key="value" value="${jre.location-1.8}"/>
        <details key="label" value="JRE 1.8 Location"/>
      </eAnnotations>
      <details key="name" value="jre.location-1.6"/>
      <details key="type" value="FOLDER"/>
      <details key="label" value="JRE 1.6 Location"/>
      <details key="description" value="The location of a JDK or JRE compatible with Java 1.6."/>
    </eAnnotations>
    <eAnnotations source="http://www.eclipse.org/oomph/setup/Variable">
      <eAnnotations source="Choice">
        <details key="value" value="${jre.location-1.8}"/>
        <details key="label" value="JRE 1.8 Location"/>
      </eAnnotations>
      <details key="name" value="jre.location-1.7"/>
      <details key="type" value="FOLDER"/>
      <details key="label" value="JRE 1.7 Location"/>
      <details key="description" value="The location of a JDK or JRE compatible with Java 1.7."/>
    </eAnnotations>
    <eAnnotations source="http://www.eclipse.org/oomph/setup/Variable">
      <details key="name" value="jre.location-1.8"/>
      <details key="type" value="FOLDER"/>
      <details key="label" value="JRE 1.8 Location"/>
      <details key="description" value="The location of a JDK or JRE compatible with Java 1.8."/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="version" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="location" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
</ecore:EPackage>
